version: "3.8"
services:
        webapp:
                image: ubuntu:latest
                container_name: my_web_app
                depends_on:
                        - redisdb
        redisdb:
                image: redis
