FROM ubuntu:latest
ENV  TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y && apt-get install apache2 -y
EXPOSE 80
CMD ["apachectl", "-D", "FOREGROUND"]
